name: Acrolinx Analyzer
description:
  A GitHub Action that analyzes and displays recent commit changes with detailed
  diffs and file modifications, and runs Acrolinx style checks on modified files
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: check-circle
  color: green

# Define your inputs here.
inputs:
  acrolinx_token:
    description:
      Acrolinx API token for style checking (can also be provided via
      ACROLINX_API_TOKEN environment variable)
    required: false
  dialect:
    description:
      Language dialect for Acrolinx analysis (e.g., american_english,
      british_english)
    required: false
    default: 'american_english'
  tone:
    description: Tone for Acrolinx analysis (e.g., formal, informal, academic)
    required: false
    default: 'formal'
  style-guide:
    description: Style guide for Acrolinx analysis (e.g., ap, chicago, apa)
    required: false
    default: 'ap'

  github_token:
    description: GitHub token for API access (uses GITHUB_TOKEN by default)
    required: false

# Define your outputs here.
outputs:
  event-type:
    description: Type of GitHub event that triggered the action
  files-analyzed:
    description: Number of files analyzed
  acrolinx-results:
    description: JSON string containing Acrolinx analysis results

# Define permissions required by the action
permissions:
  contents: write
  pull-requests: write
  statuses: write

runs:
  using: node20
  main: dist/index.js
