/**
 * PR Comment service for managing comments on pull requests
 */

import * as core from '@actions/core'
import * as github from '@actions/github'
import { AcrolinxAnalysisResult, AnalysisOptions } from '../types/index.js'
import { generateAnalysisContent } from '../utils/markdown-utils.js'
import { handleGitHubError, logError } from '../utils/error-utils.js'

/**
 * Interface for PR comment data
 */
export interface PRCommentData {
  owner: string
  repo: string
  prNumber: number
  results: AcrolinxAnalysisResult[]
  config: AnalysisOptions
  eventType: string
  rewritePrUrl?: string
}

/**
 * Generate complete comment body
 */
function generateCommentBody(
  results: AcrolinxAnalysisResult[],
  config: AnalysisOptions,
  eventType: string,
  rewritePrUrl?: string
): string {
  const header = `## 🔍 Acrolinx Analysis Results

This comment was automatically generated by the Acrolinx Analyzer GitHub Action for **${eventType}** event.`

  let content = generateAnalysisContent(results, config, header, eventType)

  // Add rewrite section if available
  if (rewritePrUrl) {
    content += `

---

## 🤖 Acrolinx Suggestions Available

We've generated improved versions of your files with Acrolinx suggestions!

### 📝 What's included
- Grammar and style improvements
- Enhanced clarity and readability
- Consistent terminology usage
- Better tone and formality

### 💡 How to apply suggestions
1. **[Review the suggestions](${rewritePrUrl})** - Check out the generated PR with all improvements
2. **Merge the suggestions** - If you're satisfied, merge the suggestion PR
3. **Manual application** - Or manually apply specific changes from the suggestion PR to your current PR

### ⚠️ Important notes
- The suggestion PR is automatically generated and will be cleaned up after 7 days
- Only merge if you're satisfied with all the suggestions
- You can review changes file by file before applying

---
*Generated by Acrolinx Analyzer GitHub Action*`
  }

  return content
}

/**
 * Find existing Acrolinx comment on PR
 */
async function findExistingAcrolinxComment(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number
): Promise<number | null> {
  try {
    const response = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: prNumber
    })

    const acrolinxComment = response.data.find((comment) =>
      comment.body?.includes('## 🔍 Acrolinx Analysis Results')
    )

    return acrolinxComment?.id || null
  } catch (error) {
    core.warning(`Failed to find existing Acrolinx comment: ${error}`)
    return null
  }
}

/**
 * Create or update PR comment with analysis results
 */
export async function createOrUpdatePRComment(
  octokit: ReturnType<typeof github.getOctokit>,
  commentData: PRCommentData
): Promise<void> {
  const { owner, repo, prNumber, results, config, rewritePrUrl } = commentData

  try {
    // Check if we have permission to comment on PRs
    try {
      await octokit.rest.repos.get({
        owner,
        repo
      })
    } catch (error: unknown) {
      const githubError = error as { status?: number }
      if (githubError.status === 403) {
        core.error(
          '❌ Permission denied: Cannot access repository. Make sure the GitHub token has "pull-requests: write" permission.'
        )
        return
      }
      throw error
    }

    const commentBody = generateCommentBody(
      results,
      config,
      commentData.eventType,
      rewritePrUrl
    )
    const existingCommentId = await findExistingAcrolinxComment(
      octokit,
      owner,
      repo,
      prNumber
    )

    if (existingCommentId) {
      // Update existing comment
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingCommentId,
        body: commentBody
      })
      core.info(`✅ Updated existing Acrolinx comment on PR #${prNumber}`)
    } else {
      // Create new comment
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body: commentBody
      })
      core.info(`✅ Created new Acrolinx comment on PR #${prNumber}`)
    }
  } catch (error: unknown) {
    const githubError = handleGitHubError(error, 'Create/update PR comment')

    if (githubError.status === 403) {
      core.error(
        '❌ Permission denied: Cannot create or update comments on pull requests.'
      )
      core.error(
        'Please ensure the GitHub token has "pull-requests: write" permission.'
      )
    } else if (githubError.status === 404) {
      core.error(
        '❌ Pull request not found. Make sure the PR exists and is accessible.'
      )
    } else {
      logError(githubError, 'Failed to create/update PR comment')
    }
  }
}

/**
 * Check if current event is a pull request
 */
export function isPullRequestEvent(): boolean {
  return github.context.eventName === 'pull_request'
}

/**
 * Get PR number from context
 */
export function getPRNumber(): number | null {
  if (github.context.eventName === 'pull_request') {
    return github.context.issue.number
  }
  return null
}
