name: Simple Commit Status Test

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  statuses: write

jobs:
  simple-test:
    name: Simple Commit Status Test
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Server URL: ${{ github.server_url }}"

      - name: Test Simple Commit Status
        run: |
          # Test with minimal data
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{
              "state": "success",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "description": "Test status",
              "context": "test"
            }'

      - name: Test with Different Description
        run: |
          # Test with shorter description
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{
              "state": "success",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "description": "Test",
              "context": "simple"
            }'

      - name: Test without target_url
        run: |
          # Test without target_url
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{
              "state": "success",
              "description": "Test no URL",
              "context": "no-url"
            }'
