name: Test Commit Status

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  test-commit-status:
    name: Test Commit Status
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        with:
          acrolinx_token: ${{ secrets.ACROLINX_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tone: formal
          dialect: american_english
          style-guide: ap

      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Server URL: ${{ github.server_url }}"
